#!/bin/perl

use warnings;
use strict;

print("Step 1: Certificado de arqueacao \t (Pegando da aba 1)\n");
#	Nome da certificadora
my $empresa;
while(<>){
	if ($_ =~ m/Empresa:,/) {
		$empresa = $_;
		$empresa =~ s/Empresa:,//;
		$empresa =~ s/\n//;
		last;
	}
}
#	Data do certificado
my $datacert; 
while(<>){
	if ($_ =~ m/Certificado:,/) {
		$datacert = $_ ;
		$datacert =~ s/Certificado:,//;
		$datacert =~ s/\n//;
		last;
	}
}
print ("$empresa $datacert");

print("Step 2: Altura util \t (Pegando da aba 1)\n");
my $vendo_altura;
my $altura_util;
while(<>){
	# Ele começa a olhar as alturas depois de encontrar a palavra Altura NA PRIMEIRA ABA!!
	if ($_ =~ m/Altura/) {	
		$vendo_altura = 1;
	} elsif ($vendo_altura) {
		# Sabemos que a sessão acaba quando aparece qualquer linha NAO começada com um numero
		if ($_ =~ m/^[0-9]/) {			
			$altura_util = $_;
		} else {
			my @firstfield = split /,/, $altura_util;
			$altura_util = $firstfield[0];
			last;
		}
	}
}

print("Step 3: Contando os aneis \t (Pegando da aba 2)\n");
my $segunda_aba		= 0;
my $aneis_counter	= 0;
my $missing		= 0;
my $comecou		= 0;
while(<>){
	# Ele começa a olhar as alturas depois de encontrar a palavra Altura NA SEGUNDA ABA!!
	if ($_ =~ m/Faixas de Arqueação/) {	
		$segunda_aba = 1;
	} elsif ($comecou) {
		if ($_ =~ m/Faixa de/) {			
			$aneis_counter++;
		} elsif ($missing) {
			last;
		} else {
			$missing++;
		}
	} elsif ($segunda_aba) {
		$comecou++;
	}
}
print("${aneis_counter}");

my $certimestamp;
my @listtemp = split /\//, $datacert;
$certimestamp = $listtemp[1];
if ($certimestamp =~ m/[0-9]{4}/) {
	#print("$certimestamp 4 vezes\n");
} else {
	$certimestamp = "20${certimestamp}";
}


#	Atribuindo anelid's

my $anelidfile = './idcount';
my $previousid = 1;
open (IC, '<', $anelidfile) or die $!;
while (<IC>) {
	if ($_ =~ m/[0-9]/) {
		if($_ > $previousid) {
			$previousid = $_;
		}
	}
}
close (IC);

$previousid++;
open (IW, '>', $anelidfile);
print IW "$previousid";
close(IW);

print("INSERT INTO arqueacoes (certarqueacao, datacertificado, alturautil, numeroaneis) VALUES ('${empresa}${datacert}', '${certimestamp}', '${altura_util}', '${aneis_counter}');\n");
