#!/bin/bash
# author: renatoexpert renatorraraujo@gmail.com

#	Tanques
echo "Cleaning id file"
echo "53" > idcount
echo "Cleaning inserts file"
echo "USE MEDLOGIXCRM" > inserts.sql

#	Ibametro
echo "Working on the following certificates"
FILES="**xls"
echo $FILES
for f in $FILES
do
	#	Convert to txt
	tf="$f.txt"
	echo "Processing $f file into $tf..."
	ssconvert $f $tf
	#	Get info
	./analizer $tf #1>> inserts.sql
	echo ---------------
done

rm **.txt
rm idcount
