#!/bin/bash
# author: renatoexpert renatorraraujo@gmail.com

#	Tanques
echo "Cleaning id file"
echo "53" > idcount
echo "Cleaning inserts file"
echo "USE MEDLOGIXCRM" > inserts.sql

#	Ibametro
echo "Working on the following certificates"
FILES="tqs/*xls"
mkdir -p problematic
echo $FILES
for f in $FILES
do
	#	Convert to txt
	tf="$f.txt"
	echo "Processing $f file into $tf..."
	ssconvert $f $tf
	#	Get info
	./analizer $tf 
	if [ $? -eq 0 ]
	then
		echo "Success"
	else
		mv $f problematic
	fi
	echo ---------------
done

rm tqs/*.txt
rm idcount
